# Generated by Django 4.0.5 on 2022-09-16 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcooperativa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Documento', models.IntegerField(primary_key=True, serialize=False)),
                ('nomusuario', models.CharField(max_length=30)),
                ('clave', models.CharField(max_length=30)),
                ('rol', models.CharField(max_length=30)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcooperativa.cliente')),
            ],
        ),
    ]
