# Generated by Django 4.0.5 on 2022-09-16 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcooperativa', '0002_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nomusuario',
            field=models.CharField(max_length=40),
        ),
    ]
